version: '3.8'

# networks:
#     shared_network:
#         external: true

services:
    postgres_db:
        container_name: postgresDB
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=some-db
        restart: always
        ports:
            - '5436:5432'
        volumes:
            # - ./ext.sql:/docker-entrypoint-initdb.d/ext.sql
            # - ./db.sql:/docker-entrypoint-initdb.d/db.sql
            # - ./mysql.conf:/etc/mysql/conf.d
            # - ./dbdata:/var/lib/mysql/:delegated
            - ./db:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin4_container
        restart: always
        ports:
          - "5050:80"
        environment:
          PGADMIN_DEFAULT_EMAIL: raj@nola.com
          PGADMIN_DEFAULT_PASSWORD: admin
        volumes:
          - ./pgadmin-data:/var/lib/pgadmin
    volumes:
        postgres_db:
            driver: local

